services:
  database:
    image: postgres:12
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment: 
     - POSTGRES_USER=ailuropoda
     - POSTGRES_PASSWORD=melanoleuca
     - POSTGRES_DB=akira_dev
