/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */

import * as PrismaClient from ".prisma/client"



declare global {
  interface NexusGenCustomOutputProperties<TypeName extends string> {
    crud: NexusPrisma<TypeName, 'crud'>
    model: NexusPrisma<TypeName, 'model'>
  }
}

declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  DateTimeFieldUpdateOperationsInput: { // input type
    set?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  GuildSettingsCreateInput: { // input type
    action: string; // String!
    id: string; // String!
    prefix?: string | null; // String
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    updatedBy?: string | null; // String
  }
  GuildSettingsUpdateInput: { // input type
    action?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    id?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    prefix?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    updatedBy?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
  }
  GuildSettingsWhereUniqueInput: { // input type
    id?: string | null; // String
  }
  StringFieldUpdateOperationsInput: { // input type
    set?: string | null; // String
  }
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  DateTime: any
}

export interface NexusGenRootTypes {
  GuildSettings: PrismaClient.GuildSettings;
  Mutation: {};
  Query: {};
}

export interface NexusGenAllTypes extends NexusGenRootTypes {
  DateTimeFieldUpdateOperationsInput: NexusGenInputs['DateTimeFieldUpdateOperationsInput'];
  GuildSettingsCreateInput: NexusGenInputs['GuildSettingsCreateInput'];
  GuildSettingsUpdateInput: NexusGenInputs['GuildSettingsUpdateInput'];
  GuildSettingsWhereUniqueInput: NexusGenInputs['GuildSettingsWhereUniqueInput'];
  StringFieldUpdateOperationsInput: NexusGenInputs['StringFieldUpdateOperationsInput'];
  String: NexusGenScalars['String'];
  Int: NexusGenScalars['Int'];
  Float: NexusGenScalars['Float'];
  Boolean: NexusGenScalars['Boolean'];
  ID: NexusGenScalars['ID'];
  DateTime: NexusGenScalars['DateTime'];
}

export interface NexusGenFieldTypes {
  GuildSettings: { // field return type
    action: string; // String!
    id: string; // String!
    prefix: string; // String!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
    updatedBy: string; // String!
  }
  Mutation: { // field return type
    createOneGuildSettings: NexusGenRootTypes['GuildSettings']; // GuildSettings!
    deleteOneGuildSettings: NexusGenRootTypes['GuildSettings'] | null; // GuildSettings
    updateOneGuildSettings: NexusGenRootTypes['GuildSettings'] | null; // GuildSettings
  }
  Query: { // field return type
    guildSettings: NexusGenRootTypes['GuildSettings'][]; // [GuildSettings!]!
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    createOneGuildSettings: { // args
      data: NexusGenInputs['GuildSettingsCreateInput']; // GuildSettingsCreateInput!
    }
    deleteOneGuildSettings: { // args
      where: NexusGenInputs['GuildSettingsWhereUniqueInput']; // GuildSettingsWhereUniqueInput!
    }
    updateOneGuildSettings: { // args
      data: NexusGenInputs['GuildSettingsUpdateInput']; // GuildSettingsUpdateInput!
      where: NexusGenInputs['GuildSettingsWhereUniqueInput']; // GuildSettingsWhereUniqueInput!
    }
  }
  Query: {
    guildSettings: { // args
      after?: NexusGenInputs['GuildSettingsWhereUniqueInput'] | null; // GuildSettingsWhereUniqueInput
      before?: NexusGenInputs['GuildSettingsWhereUniqueInput'] | null; // GuildSettingsWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
    }
  }
}

export interface NexusGenAbstractResolveReturnTypes {
}

export interface NexusGenInheritedFields {}

export type NexusGenObjectNames = "GuildSettings" | "Mutation" | "Query";

export type NexusGenInputNames = "DateTimeFieldUpdateOperationsInput" | "GuildSettingsCreateInput" | "GuildSettingsUpdateInput" | "GuildSettingsWhereUniqueInput" | "StringFieldUpdateOperationsInput";

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = "Boolean" | "DateTime" | "Float" | "ID" | "Int" | "String";

export type NexusGenUnionNames = never;

export interface NexusGenTypes {
  context: { prisma: PrismaClient.PrismaClient };
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  allTypes: NexusGenAllTypes;
  inheritedFields: NexusGenInheritedFields;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractResolveReturn: NexusGenAbstractResolveReturnTypes;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
}